services:
  pubg_tournament:
    container_name: pubg_tournament
    build:
      context: .
    env_file: secrets.env
    ports:
      - ${PORT:-5000}:5000
    volumes:
      - ./instance:/app/instance
